### ISSUE TITLE
Attention

### ISSUE THREAD

**Issue by davawen** [NSAILLE-POWER5/spaze#1]
Oyé oyé @CyanUnderscore @Baronsabron @MiKL11112006 @adrienlebgdu26 
J'ai bougé toutes les images et tout les shaders dans des dossier, et j'ai séparé le code en plusieurs fichiers dans 01126e8be44e546a8815de0bc23e9bced5bf55fd.

C'est juste pour vous dire de faire attention et que, si vous avez modifié la classe Planète (par exemple), il faudrait bouger vos changement dans le bon fichier.

**Comment by Baronsabron** [comment]
@davawen je vien de prendre ton code avec les trous de ver et j'ai cette erreur 
Traceback (most recent call last):
  File "C:\Users\HP\PycharmProjects\spaze\main.py", line 399, in <module>
    main()
  File "C:\Users\HP\PycharmProjects\spaze\main.py", line 99, in main
    sys = system.new_sys()
          ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\PycharmProjects\spaze\system.py", line 135, in new_sys
    system.add(Planet(500 + randint(175, 250)*i, system.bodies[0], self.G, 0.075*radius//1, radius))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\PycharmProjects\spaze\system.py", line 43, in __init__
    self.colors = self.gen_layer() 
                  ^^^^^^^^^^^^^^^^
  File "C:\Users\HP\PycharmProjects\spaze\system.py", line 88, in gen_layer
    layer_3 = Color(round((1-self.oxygen/20)*255), round((1-self.oxygen/20)*255), 10, 255)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\pyray\__init__.py", line 80, in func
    return ffi.new(f"struct {struct} *", args)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OverflowError: can't convert negative number to unsigned
Voila c'etait pour te le dire

**Comment by davawen** [comment]
En effet

**Comment by davawen** [comment]
C'est fix avec d9805f1
